### ISSUE TITLE
Phone number input can exceed 8 digits

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-4/main#115]
**Please describe the problem**
Phone number could exceed 8 digits.
**Describe the improvement you'd like to suggest**
Normally numbers in singapore is 8 digits so maybe limit to 8

<hr>

**Reported by:** @ngkaicong
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#68]</sub>

**Comment by shanseet** [comment]
phone num now min 8 digits, max 15 digits, + sign allowed in front to allow for international numbers.
