### ISSUE TITLE
Email and date checks

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-4/main#116]
**Please describe the problem**
Date and Email input can exceed and be of error

**Describe the improvement you'd like to suggest**
Limit the date of birth to the current year and email domains to @something.com 

![Screenshot 2019-04-03 at 12 51 27 PM](https://user-images.githubusercontent.com/13186268/55453638-3f6b3700-560f-11e9-9247-75d7c9b7ec0d.png)

<hr>

**Reported by:** @ngkaicong
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#87]</sub>

**Comment by weizhang05** [comment]
Bug severity is changed to low.

Rationale: 
- It is possible that someone might use an email belonging to a personal domain, thus not practical as can't do a proper check if it's a valid email without having network access (project constraint)
- Year for DOB definitely can be restricted, but not practical to restrict it to current year

Note: Emails with the format of xxx@yyy is a valid email. Thus, checking if a TLD (Top Level Domain) exists will not be needed.

Instead, the following will be proposed and be implemented:
- We shall based on the assumption "there will not be a case where participants are older than 50 years old"
