### ISSUE TITLE
Excel feature not working

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-4/main#117]
**Describe the bug**
Cannot use export feature

**Expected behavior**
To export data to excel file

**Screenshots**
![Screenshot 2019-04-03 at 1 05 08 PM](https://user-images.githubusercontent.com/13186268/55454130-409d6380-5611-11e9-94ff-7219237fa0dc.png)

<hr>

**Reported by:** @ngkaicong
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#143]</sub>

**Comment by ssunil3232** [comment]
The command was not yet done. Now it is.
