### ISSUE TITLE
Update UG

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-4/main#118]
**Describe the bug**
Examples provided not correct when copied. 

**To Reproduce**
Provide correct examples 

<hr>

**Reported by:** @ngkaicong
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#178]</sub>

**Comment by weizhang05** [comment]
Severity changed to low.

Rationale: Does not crashes the system.
