### ISSUE TITLE
Deleting a non_empty group

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-4/main#119]
**Describe the bug**
Group should be emptied before deletion but deletion of non empty groups allowed

**To Reproduce**
1. Add House "Blue"
2. Add Group "B1"
3. Add group "B2"
4. List
5. Edit 1 g/b1
6. Edit 2 g/b2
7. Delete_g b1

**Expected behavior**
Error expected. But group is deleted and participants are still in deleted groups.

<hr>

**Reported by:** @e0176106
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#209]</sub>

**Comment by shanseet** [comment]
Followed steps but cannot reproduce error. Will keep trying, but put severity at low for now.
